before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libapr1 openssl
language: java
jdk:
#- openjdk7 #https://github.com/travis-ci/travis-ci/issues/5227
- oraclejdk7
- oraclejdk8
env:
- SG_ALLOW_OPENSSL=true
- SG_ALLOW_OPENSSL=false
after_success:
- mvn clean cobertura:cobertura coveralls:report
notifications:
  slack:
    secure: Khv11C+3zyd7dKqGRiB6oXOXYNd6DuFWaV2q0sAWD3sEdeN8Gnxxto/NHr7Wu4Mlh8S2I0bnegZ/1CYZTyvBjo9H/D+v1WfWN1OnsOHy0jWeUPL/7ho172WVZYnh/x3CJNc+05QCTB4zOZEYIO6jKeroPbrLeiUDPEK/T+FWQwmP1zvR4gV1HMLqFAJX0FoqPyh1qROgwaBQamrWP9U1i+VgxRt7rJLLOc48qe12J2hlMgzDy1LCSJvrOejNA11CRcFoWWGzDV0MIqn1EEpQdmYNpL8fQOpK1my4OC+V34Q+TnjuC3R93AqliCm/nHYx9wzOd7l7jdmuPDvkEbdGTI3mTYrD06jJZ3omoGiIkickb8bR+01cqgGr1OTj09c4Qqo4nCMDdjBkRILECmXlABe4agZpOlQ/weV+WNxS8GzAUQnTlenRDrOIlAtdMjju6XLe96Sc3CoEXVRrYN/ZTbZuceqyOhcRfaL9Yr5fqqtltMM8UTy9ib+wmRO02xhiCHdQGbzmoiVNzltFTiNR0S2fW1Dr/L0wsl8Q5b7WWof5R0mFPslnqlQ/LdfPBBYiSHMPrM1ydfpGb8e0PSOH4HPrM3EVRh7OrjEHAB+zKpuDLLQYcXwUE7o3GOmnsSErcYTKoLOhPKdQZAEq5cb7EgNLHJdrGx7QR3ic75PAXJk=
