searchguard:
  dynamic:
    http:
      xff:
        enabled: false
        internalProxies: 192\.168\.0\.10|192\.168\.0\.11
        remoteIpHeader: "x-forwarded-for"
        proxiesHeader: "x-forwarded-by"
        trustedProxies: "proxy1|proxy2"
      authenticator:  
        type: com.floragunn.searchguard.http.HTTPBasicAuthenticator
    authcz:
      authentication_domain_basic_internal:
        enabled: true
        order: 0
        authentication_backend:
          type: com.floragunn.searchguard.auth.internal.InternalAuthenticationBackend
        authorization_backend:
          type: com.floragunn.searchguard.auth.internal.NoOpAuthorizationBackend
      #authentication_ldap:
        #enabled: true
        #order: 1
        #authentication_backend:
          #type: com.floragunn.dlic.auth.ldap.backend.LDAPAuthenticationBackend
          #config:
            #host: ["",""]
        #authorization_backend:
          #type: com.floragunn.dlic.auth.ldap.backend.LDAPAuthorizationBackend
      #authentication_domain_proxy:
        #enabled: true
        #order: 0
        #authentication_backend:
          #type: com.floragunn.searchguard.auth.internal.NoOpAuthenticationBackend
        #authorization_backend:
          #type: com.floragunn.searchguard.auth.internal.NoOpAuthorizationBackend
    