#
# HTTP
#   basic (challenging) PREAUTH?
#   proxy (not challenging, needs xff)
#   kerberos (challenging) NOT FREE FOR COMMERCIAL USE PREAUTH?
#   clientcert (not challenging, needs https)

# Authc
#   internal
#   noop
#   ldap  NOT FREE FOR COMMERCIAL USE

# Authz
#   ldap  NOT FREE FOR COMMERCIAL USE
#   noop

searchguard:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: 192\.168\.0\.10|192\.168\.0\.11
        remoteIpHeader: "x-forwarded-for"
        proxiesHeader: "x-forwarded-by"
        trustedProxies: "proxy1|proxy2"
    authc:
      kerberos:
        enabled: false
        order: 0
        http_authenticator:
          type: kerberos
          config:
            krb_debug: true
            krb5_file_path: /etc/krb5.conf
            acceptor_principal: 'HTTP/localhost'
            acceptor_keytab_path: eskeytab.tab
            strip_realm_from_principal: true
        authentication_backend:
          type: noop
      basic_internal:
        enabled: true
        order: 1
        http_authenticator:
          type: basic
        authentication_backend:
          type: intern
      ldap:
        enabled: false
        order: 2
        http_authenticator:
          type: basic
        authentication_backend:
          type: ldap
          config:
            ldaps:
              ssl:
                enabled: false
            hosts:
              - localhost:8389
            usersearch: '(uid={0})'
            userbase: 'ou=people,dc=example,dc=com'
    authz:    
      roles_from_myldap:
        enabled: false
        authorization_backend:
          type: ldap
          config:
            hosts:
              - localhost:8389
            rolesearch: '(uniqueMember={0})'
            resolve_nested_roles: true
            rolebase: 'ou=groups,dc=example,dc=com'
            rolename: cn